# Generated by Django 4.1.1 on 2022-10-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_info', '0002_student_image_alter_student_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
