# Generated by Django 4.1.1 on 2022-10-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_info', '0005_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
